//@version=4
study("BANE_derivetive")

symbol = input("BTC")
stable = "USD" //bybitがインバースかUSDTか
usd_base = "COINBASE" //bybitインバースの比較先
area_max = 0.5 //異常値でるとグラフが見づらくなるのでMAX,MIN
area_min = -0.25 

//---------------------------

binance_kairi(symbol)=>
   fx = security("BINANCE:"+symbol+"USDTPERP",timeframe.period,close)
   spot = security("BINANCE:"+symbol+"USDT",timeframe.period,close)
   kairi = max(min((fx - spot) / spot *100,area_max),area_min)

ftx_kairi(symbol)=>
   fx = security("FTX:"+symbol+"PERP",timeframe.period,close)
   spot = security(usd_base + ":"+symbol+"USD",timeframe.period,close)
   kairi = max(min((fx - spot) / spot *100,area_max),area_min)

bybit_kairi(symbol,stable)=>
   fx = security("BYBIT:"+symbol+stable,timeframe.period,close)
   spot_market = stable=="USDT" ? "BINANCE" : usd_base //USDTの時はbinanceを基準に
   spot = security(spot_market+":"+symbol+stable,timeframe.period,close)
   kairi = max(min((fx - spot) / spot *100,area_max),area_min)

//---------------------------

binance= binance_kairi(symbol)
plot(binance,title="Binance",linewidth=1,color=#ff4500,transp=70,style=plot.style_area)

bybit= bybit_kairi(symbol,stable)
plot(bybit,title="Bybit",linewidth=1,color=#008000,transp=70,style=plot.style_area)

ftx= ftx_kairi(symbol)
plot(ftx,title="FTX",linewidth=1,color=#191970,transp=70,style=plot.style_area)


hline(0, title="Zero Line",color=#999999)